import {StyleSheet} from 'react-native';
import colors from '../../../theme/colors/colors';

export default StyleSheet.create({
  container: {
    backgroundColor: 'white',
    width: '100%',
    height: '100%',
    padding: '5%',
  },
  gorevBitisContainer: {},
  gorevBitisHeaderCont: {
    paddingBottom: '5%',
  },
  gorevBitisHeaderText: {
    color: colors.dark,
    fontWeight: '500',
    fontSize: 18,
  },
  gorevBitisTarihCont: {
    width: '60%',
    height: '20%',
    backgroundColor: '#F4F4F4',
    justifyContent: 'center',
    padding: '2%',
    borderRadius: 10,
    shadowOffset: {width: 8, height: 8},
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    elevation: 5,
    shadowRadius: 1,
  },
  gorevBitisTarihText: {},
  gorevTanimiCont: {height: '40%'},
  gorevTanimiHeaderTextCont: {paddingBottom: '5%'},
  gorevTanimiHeaderText: {color: colors.dark, fontWeight: '500', fontSize: 18},
  gorevTanimiTextCont: {
    width: '100%',
    height: '80%',
    backgroundColor: '#F4F4F4',
    justifyContent: 'center',
    padding: '2%',
    borderRadius: 10,
    shadowOffset: {width: 8, height: 8},
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    elevation: 5,
    shadowRadius: 1,
  },
  gorevTanimiText: {color: colors.dark},
  gorevBasligiCont: {flexDirection: 'row', marginTop: 10},
  gorevPuanCont: {
    backgroundColor: 'yellow',
    width: 50,
    height: 50,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gorevPuanText: {
    color: colors.dark,
    fontWeight: '500',
    fontSize: 20,
  },
  gorevBasligiTextCont: {justifyContent: 'center', marginLeft: 10},
  gorevBasligiText: {
    color: colors.dark,
    textAlign: 'center',
    fontWeight: '800',
    fontSize: 20,
  },
  gorevlendirilenPHeaderTextCont: {paddingVertical: '5%'},
  gorevlendirilenPHeaderText: {
    color: colors.dark,
    fontWeight: '500',
    fontSize: 18,
  },
  gorevlendirilenPTextCont: {
    elevation: 5,
    width: '100%',
    height: '45%',
    backgroundColor: '#F4F4F4',
    borderRadius: 10,
    shadowOffset: {width: 8, height: 8},
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    shadowRadius: 1,
    justifyContent: 'center',
    padding: '2%',
  },
  gorevlendirilenPText: {
    fontStyle: 'italic',
    fontWeight: '400',
    color: '#2736C1',
  },
});
