import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  inputContainer1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#79EFFF',
    height: '10%',
    width: '95%',
    paddingRight: 5,
    paddingLeft: 5,
    fontSize: 16,
    minHeight: 40,
    margin: 7,
    borderRadius: 15,
  },
  inputContainer2: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#79EFFF',
    height: '10%',
    width: '95%',
    justifyContent: 'space-between',
    paddingRight: 5,
    paddingLeft: 5,
    fontSize: 16,
    minHeight: 40,
    margin: 7,
    borderRadius: 15,
  },
  inputContainer3: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#79EFFF',
    height: '30%',
    width: '95%',
    justifyContent: 'space-between',
    paddingRight: 5,
    paddingLeft: 5,
    fontSize: 16,
    minHeight: 40,
    margin: 7,
    borderRadius: 15,
  },
  iconContainer: {
    padding: 3,
    backgroundColor: '#D9D9D9',
    borderRadius: 50,
    width: '8%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageStyle: {
    height: 15,
    width: 15,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  input: {
    marginLeft: 5,
  },
});
